[build]
  command = 'echo hello world'
  publish = 'static/'

[template]
  incoming-hooks = ["Uniform"]

[template.environment]
  REACT_APP_OPTIMIZE_API_KEY = 'your Uniform Optimize API key'
  REACT_APP_OPTIMIZE_ORIGIN = 'https://uniformoptimize.netlify.app'
  REACT_APP_CONTENTFUL_SPACE_ID = 'paste your Contentful space ID'
  REACT_APP_CONTENTFUL_ACCESS_TOKEN = 'paste a Contentful CDA access token to pull content'