[build]
  command = 'echo hello world'
  publish = 'static/'

[template]
  incoming-hooks = ["Uniform"]

[template.environment]
  REACT_APP_OPTIMIZE_API_KEY = 'Uniform Optimize API Key'
  REACT_APP_OPTIMIZE_ORIGIN = 'Uniform Optimize Origin'
  REACT_APP_CONTENTFUL_SPACE_ID = 'Contentful Space ID'
  REACT_APP_CONTENTFUL_ACCESS_TOKEN = 'Contentful Access Token'